### ISSUE TITLE
Arabic encoding not working.

### ISSUE THREAD

**Issue by Kishanspaceo** [imgix/imgix-swift#25]
I am using imgix and it crash for following url.
"https://imgix.net/live/menu_items/photos/1291/e1eefb34a6b7c415873a0fdd31969af86704f0d/ج_مع_الراب_الرومى.jpg"

it crashes while buildURL is called.

**Comment by sherwinski** [comment]
Hi @Kishanspaceo,

It appears that the URL you provided has a bad domain (`imgix.net`). You can find the domain for your source in the imgix dashboard [source view](https://dashboard.imgix.com/sources). And for more information, feel free to read through our [documentation](https://docs.imgix.com/setup/serving-images) on serving images.

If fixing that still does not work for you, could you please provide a code example and any associated error message you get when calling `buildURL`? Thank you!

**Comment by Kishanspaceo** [comment]
I have a url like "https://myproject.imgix.net/staging/photos/196341/e47eefb34a6b7c415873a0f8945216704f0d/جبن_مع_الراب_الرومى.jpg"



I am trying to build url with 2 portions...
- myproject.imgix.net
- staging/photos/196341/e47eefb34a6b7c415873a0f8945216704f0d/جبن_مع_الراب_الرومى.jpg

But it crashes, as it has arabic characters.
My code is also working, when we have all english characters and it successfully generate the url.

It says 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents setPercentEncodedPath:]: invalid characters in percentEncodedPath'

**Comment by Kishanspaceo** [comment]
let client = ImgixClient.init(host: "myproject.imgix.net")
let url = client.buildUrl("staging/photos/196341/e47eefb34a6b7c415873a0f8945216704f0d/جبن_مع_الراب_الرومى.jpg", params: [
            "w": 300,
            "h": 300,
            "fit": "crop"
        ])
        debugPrint(url)

**Comment by sherwinski** [comment]
Hi @Kishanspaceo,

Thank you for providing these examples, they are very helpful. I am currently investigating this issue and hope to have an solution for you sometime this week.

**Comment by Kishanspaceo** [comment]
in the function  func sanitizePath(_ path: String) -> String
after declaring path variable,
 **path = path.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? path**
adding above line would work.

**Comment by sherwinski** [comment]
Hi @Kishanspaceo, the fix for this issue is now available via [v1.1.2](https://github.com/imgix/imgix-swift/releases/tag/1.1.2) 🎉
