### ISSUE TITLE
invalid signatures for comma-separated values without base64 encoding

### ISSUE THREAD

**Issue by bcherry** [imgix/imgix-swift#3]
I'm trying to use the Imgix-Swift library to generate signed imgix URLs in an objective-c iPhone application.

Unsigned, my URL looks like this:

`https://host/94BAB140-493B-453F-97CE-739C2685B88A.jpg?or=1&w=488&h=488&fit=max&auto=redeye&rect=1626,652,848,848`

When I try to build a signed URL with `ImgixClient -buildURL:params:`, I get this

`https://host/94BAB140-493B-453F-97CE-739C2685B88A.jpg?ixlib=swift-0.1.2&h=488&rect=1626%2C652%2C848%2C848&or=1&w=488&auto=redeye&fit=max&s=f3a7f97bfa05a0fe584c5151fe69e87a`

This results in a 401.

If instead, I use the base-64 parameters, I get this:

`https://host/94BAB140-493B-453F-97CE-739C2685B88A.jpg?auto64=cmVkZXll&rect64=MTYyNiw2NTIsODQ4LDg0OA&ixlib=swift-0.1.2&w64=NDg4&or64=MQ&fit64=bWF4&h64=NDg4&s=871421f2c35975e750211f222037c58e`

This works just fine.

I adjusted my input, and narrowed the problematic parameter down to `rect`, which has a comma-separated value.

**Comment by paulstraw** [comment]
Ah, very interesting. I'll take a look at this now.
