### ISSUE TITLE
iOS 9.0

### ISSUE THREAD

**Issue by jndonald3** [imgix/imgix-swift#5]
I'm getting the following error when building the latest release with carthage:
Module file's minimum deployment target is ios9.3 v9.3.

My guess is that this occurs because the minimum deployment target for my app is iOS 9.0 which is lower than the deployment target for the imgix-swift sdk(9.3). Is it possible to have the deployment target lowered for imgix-swift?

**Comment by paulstraw** [comment]
All set + released as 0.1.4!
